version: 2
jobs:
  deploy:
    docker:
      - image: circleci/python:3-node
    steps:
      - checkout
      - run: yarn
      - run: yarn build-storybook
      - run: sudo pip install awscli
      - run: aws s3 sync .out s3://terenceodonoghue.dev/velocity-ui/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
